### ISSUE TITLE
Figure out who's coming

### ISSUE THREAD

**Issue by davclark** [dlab-berkeley/social-data-carpentry-2015#1]
@jonstiles, @rochelleterman, and I (@davclark) got together last week and decided that we'd like to shoot for a _social_ Data Carpentry hackathon July 24-25 (@jonstiles and I had previously discussed this with @tracykteal). The hackathon proper will be Friday-Saturday, with a more social day on Sunday (July 26). [Data Carpentry](http://datacarpentry.org) is an offshoot of Software Carpentry with a focus on data preparation, management, analysis, sharing, etc.

The goal would be to attract the broader bay area community, with select folks from far away flying in, and probably a focus on setting up remote collaboration _after_ the event. It'd be nice to have an open video-conference maybe late Friday or early Saturday to get a check in from the broader community, which might include other Data Carpentry folks who are not social science oriented, and folks who are simply not able to make it.

If all goes well, we'll shoot for a Social Data Carpentry training at the beginning of the Fall semester in some combination of D-Lab / BIDS, etc.
## RSVP

**Please indicate in the comments below if you plan on coming. I'll add you to the team that has admin access to this repo.**

Specifically, please also mention which of the following you are good for:
- Showing up!
- Money
- Preparing materials (text, code, etc.) so that the hackathon will be productive
- Publicity
- Leadership / teaching during the hackathon

Did I miss anything?

**Comment by stefanv** [comment]
I will show up, I don't need money (or have money to give), I can help with preparing materials, I can only tweet for publicity, I'm happy to teach / mentor in my fields of expertise (mostly scientific Python tools, git, etc.).

**Comment by EvanMisshula** [comment]
I can bring enthusiasm for python, git and reproducibility. I am a grad student on the East Coast so help with accommodations  is welcome.  I need a couch not a hotel suite.

**Comment by davclark** [comment]
Note, I've made a number of folks admins... feel free to invite others to the dlab-berkeley/dlab-data-carpentry team!

**Comment by jonstiles** [comment]
Is this the data carpentry hackathon, something that it morphed into, or
something completely different?

On Mon, Apr 27, 2015 at 8:01 PM, Dav Clark notifications@github.com wrote:

> We'll have a hackathon July 24-25th. We'll plan to do something nice
> together to celebrate on the 26th. Please indicate in the comments below if
> you plan on coming. I'll add you to the team that has admin access to this
> repo.
> 
> Specifically, please also mention which of the following you are good for:
> - Showing up!
> - Money
> - Preparing materials (text, code, etc.) so that the hackathon will be
>   productive
> - Publicity
> - Leadership / teaching during the hackathon
> 
> Did I miss anything?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dlab-berkeley/social-software-carpentry-2015/issues/1
> .

## 

Jon Stiles
D-Lab
California Census Research Data Center
UC Data Archive & Technical Assistance
http://dlab.berkeley.edu

**Comment by davclark** [comment]
Thanks @jonstiles for pointing out some confusion. I've fixed the name to be _data_ carpentry, and added a more complete description above.

**Comment by jonstiles** [comment]
I can show up. 
I think I can bring some money/catering.
Materials/publicity/teaching - I think so.

**Comment by Charlotte23** [comment]
I will show up. 
I can think about founding...

**Comment by rochelleterman** [comment]
I will show up!
I don't have any money :(
I can do a (limited) amount of prep materials!
And publicity!
And teaching!

**Comment by tracykteal** [comment]
I'll be there! I can prepare materials, work on publicity and help with leadership/teaching during the hackathon. Although as not-a-social-scientist, I can help more on the structure of a Data Carpentry hackathon and how lessons can be structured and assessment built in.

**Comment by davclark** [comment]
Yeah!

@tracykteal, @davclark, and @rochelleterman will coordinate contacting people on this [super-secret google doc](https://docs.google.com/a/berkeley.edu/document/d/1Rdjo6QKw-H1BBrN__h3Kt26yCdDIbwk4CfS76v9Pza8/edit?usp=sharing) (let Dav know if you want access).

**Comment by pattyf** [comment]
I would love to join in on July 24 but will be out of town July 25th. I can
help with materials and publicity.

Patty

On Tue, May 26, 2015 at 9:48 PM, Dav Clark notifications@github.com wrote:

> Yeah!
> 
> @tracykteal https://github.com/tracykteal, @davclark
> https://github.com/davclark, and @rochelleterman
> https://github.com/rochelleterman will coordinate contacting people on
> this super-secret google doc
> https://docs.google.com/a/berkeley.edu/document/d/1Rdjo6QKw-H1BBrN__h3Kt26yCdDIbwk4CfS76v9Pza8/edit?usp=sharing
> (let Dav know if you want access).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dlab-berkeley/social-data-carpentry-2015/issues/1#issuecomment-105754828
> .

## 

Patty Frontiera
Academic Coordinator
D-Lab, _Supporting Data Intensive Social Science for All_
356 Barrows Hall, University of California Berkeley
http://dlab.berkeley.edu

**Comment by jiffyclub** [comment]
I can come Friday, July 24 only. I can help people with Python and Git.

**Comment by benmarwick** [comment]
Can't come sadly, but love the idea and can confirm demand for it at UW, especially through the [CSSS](https://www.csss.washington.edu/) and @uwescience. 

I've had great success using @swcarpentry and @datacarpentry materials with social science students (including my small contribution on [text mining using R](https://github.com/datacarpentry/textmining-socialsci)), and would recommend some of the content from the other carpentries be reused in this social science one with minor adustments. The lessons on [spreadsheets](https://github.com/datacarpentry/excel-ecology) and [tidy data](https://github.com/datacarpentry/R-tidy-data-LoR) are excellent. Many of the @Reproducible-Science-Curriculum lessons have also been good value for my social science students, particularly the one on [organisation](https://github.com/Reproducible-Science-Curriculum/rr-organization1)

And of course use of the winning pedagogical techniques of live coding, sticky notes, multiple-choice questions, etc. would be great in the social sciences also. Can't wait to see what you guys come up with, and I look forward to using it!

**Comment by davclark** [comment]
Awesome! I want to flag that there's tons of useful stuff in the above. We
should definitely include the text mining lesson, and also adapt from the
OpenRefine lesson for Ecology.

Best,
D

On Thu, Jul 16, 2015 at 11:40 AM, Ben Marwick notifications@github.com
wrote:

> Can't come sadly, but love the idea and can confirm demand for it at UW,
> especially through the CSSS https://www.csss.washington.edu/ and
> @uwescience https://github.com/uwescience.
> 
> I've had great success using @swcarpentry https://github.com/swcarpentry
> and @datacarpentry https://github.com/datacarpentry materials with
> social science students (including my small contribution on text mining
> using R https://github.com/datacarpentry/textmining-socialsci), and
> would recommend some of the content from the other carpentries be reused in
> this social science one with minor adustments. The lessons on spreadsheets
> https://github.com/datacarpentry/excel-ecology and tidy data
> https://github.com/datacarpentry/R-tidy-data-LoR are excellent. Many of
> the @Reproducible-Science-Curriculum
> https://github.com/Reproducible-Science-Curriculum lessons have also
> been good value for my social science students, particularly the one on
> organisation
> https://github.com/Reproducible-Science-Curriculum/rr-organization1
> 
> And of course use of the winning pedagogical techniques of live coding,
> sticky notes, multiple-choice questions, etc. would be great in the social
> sciences also. Can't wait to see what you guys come up with, and I look
> forward to using it!
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/dlab-berkeley/social-data-carpentry-2015/issues/1#issuecomment-122045700
> .

## 

Dav Clark
Data Scientist
Berkeley D-Lab + BIDS
bead.glass
917-544-8408

**Comment by tracykteal** [comment]
Thanks @jiffyclub This is a discussion/hackathon so I'm not sure how much Python and git-ing there will be, but it would be great to have you there!

**Comment by rdhyee** [comment]
I'm interested in showing up for part of the hackathon on Friday.

**Comment by michaellevy** [comment]
I can't make this weekend but would like to be involved in the future. Is there a group I can join or something?

**Comment by davclark** [comment]
This issue should be enough to guarantee we get in touch. Welcome aboard, and watch this space for more!

**Comment by jiffyclub** [comment]
Something came up and I won't be coming tomorrow after all.

**Comment by katyhuff** [comment]
I can show up in the morning tomorrow. I can bring my github issue-closing skills, some dollars for pizza or whatever, and tweets.

**Comment by tracykteal** [comment]
For people who can't make it, we will have Adobe Connect for remote attendance. 

http://idigbio.adobeconnect.com/room/
This room will be active from 9am - 11:30am and 1:30pm - 6:00pm Pacific on Friday, and 9am - 6pm on Saturday. 

Let us know if you have any trouble connecting.

**Comment by tracykteal** [comment]
For those who can't attend in person, we have an Adobe Connect meeting room so you can attend virtually

http://idigbio.adobeconnect.com/room

You should be able to go to that URL and log in as a guest.
