### ISSUE TITLE
Get R materials from Clara Cohen & Chris Krogslund

### ISSUE THREAD

**Issue by davclark** [dlab-berkeley/social-data-carpentry-2015#3]
Materials from others are also of course very welcome.

@davclark is very interested in Hadley Wickam's "tidy R" pipeline approach.

**Comment by rochelleterman** [comment]
Here's my R demo from the Hacker WIthin: https://github.com/rochelleterman/R-hacker-within

**Comment by rochelleterman** [comment]
Here's @ckrogs "Useful Stuff in R" lesson: https://github.com/ckrogs/r_useful_dlab

**Comment by davclark** [comment]
Clara's stuff is [here](http://linguistics.berkeley.edu/~cpccohen/Workshops.html).

**Comment by davclark** [comment]
Just got permission to use Clara's materials as long as she gets credit (in my email)

**Comment by davclark** [comment]
Moving things to #4
